### ISSUE TITLE
Failed to acquire connection: handle doesn't contain a supported display type

### ISSUE THREAD

**Issue by MathiasYde** [Fuzzyzilla/octotablet#7]
Hello, the example project compiles and runs on my Pop!_OS computer, but it's seemingly incompatible with my Wacom 16" tablet (which should be supported according to the readme)

![Screenshot from 2024-04-18 21-03-26](https://github.com/Fuzzyzilla/octotablet/assets/35201354/d860b691-0106-422f-831d-2bb5f2d9aed5)

inxi dump
```bash
System
  Host: pop-os Kernel: 6.8.0-76060800daily20240311-generic x86_64 bits: 64
    Desktop: GNOME 42.5 Distro: Pop!_OS 22.04 LTS
```

**Comment by Fuzzyzilla** [comment]
Hello!

Currently, octotablet supports Wayland desktops, but not Xorg. Pop_OS only provides Xorg support - [although it seems possible to enable wayland](https://unix.stackexchange.com/questions/700938/enable-wayland-in-popos-22-04) - at current, the wayland implementation is a bit buggy under Pop_OS so it is not made available by default.

Xorg support is top of my priorities for this crate! Unfortunately I have not had much time to implement it, but it still is very much a goal as I understand a large portion of the desktop Linux community still uses it.

Thank you for the report!

**Comment by Fuzzyzilla** [comment]
I suppose I should only mark this as closed when it's actually fixed, huh? :P
Sorry bout that.

**Comment by MathiasYde** [comment]
Haha that's okay. To be honest, I don't really have much Linux literacy so terms like Wayland and Xorg fly right over my head. I've recently switched to Pop!_OS after Microsoft's astrocious plan to incorporate AI and ads into Windows.

Are you currently working on the Xorg implementation for this crate?

**Comment by MathiasYde** [comment]
Oh wow, I see the favor of Wayland over Xorg. I followed this [StackOverflow answer](https://unix.stackexchange.com/a/730441) and enabled Wayland on my Pop!_OS machine which made the examples work (The eframe-viewer example is so cool), I had some issues with my displays but a simple reboot fixed it :)

I think I just assumed that I already had enabled Wayland since I saw many crates with similar names while compiling Rust code, and Blender/Krita also recognized my Wacom tablet on Xorg (But I suppose they also have a bit more man-power than just you on this repo)

**Comment by Fuzzyzilla** [comment]
Yay!! I am glad it is working for you! I had a lot of fun with that egui-viewer example, I may have gone a bit too far with the fanciness :P

I have moved discussion of X11 implementation over to #10.
